--- #YAML:1.0
name:               Dpchrist-Scripts
version:            1.012
abstract:           Perl scripts by David Christensen
author:
    - David Paul Christensen dpchrist@holgerdanske.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dpchrist::Debug:     1.044
    Dpchrist::LangUtil:  1.013
    Dpchrist::Module:    1.026
    feature:             0
    File::Slurp:         0
    Getopt::Long:        0
    Pod::Html:           0
    Pod::Text:           0
    Pod::Usage:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
